#! /bin/bash

#Exit on errors
set -e

# Run like this:
# qsub -N ..... ./1_train_start

echo 
echo "Beginning training."
echo "  Script:      `basename $0`"
echo "  Date:        `date`"
echo "  Hostname:    `hostname`"
echo "  PBS_GPUFILE: $PBS_GPUFILE"
if [ "$PBS_GPUFILE" = "" ]; then
    echo "  --> WARNING: No PBS_GPUFILE, so we're not sure which GPU to use. Trying default."
else
    ls $PBS_GPUFILE >/dev/null || echo "Error: PBS_GPUFILE $PBS_GPUFILE not found."
    gpustring=`cat $PBS_GPUFILE`
    gpunum=`echo $gpustring | egrep -o 'gpu[0-9]' | egrep -o [0-9]`
    if [ "$gpunum" = "" ]; then
        echo "Error: gpunum is blank"
        exit 1
    fi
    export CUDA_VISIBLE_DEVICES=$gpunum
    echo "  GPU String:  $gpustring"
    echo "  Using GPU:   $CUDA_VISIBLE_DEVICES"
fi
echo "  nvidia-smi:"
echo
nvidia-smi | sed 's/^/    /g'
echo
echo "  Files here:"
echo
ls -ralt | sed 's/^/    /g'
echo
echo "  Dataset sizes:"
echo
du -sh imagenet_train_leveldb imagenet_val_leveldb | sed 's/^/    /g'
echo
echo "  env:"
echo
env | sed 's/^/    /g'
echo


# FIRST: Figure out if we're supposed to be fine-tuning or not:
finetune_base_net_file=`ls -rt basenet/caffe_imagenet_train_iter_*[0-9] 2>/dev/null | tail -n 1`  # Take latest previous, even iter_0
if [ "$finetune_base_net_file" = "" ]; then
    echo "Fine-tuning: We are not fine-tuning another network."
else
    echo "Fine-tuning: We are fine-tuning another network."
    echo "Fine-tuning: Base network file (only used if traing from scratch): $finetune_base_net_file"
fi

# SECOND: Figure out if we should resume or start fresh, regardless of whether we're fine-tuning or not
lastfile=`ls -rt *solverstate 2>/dev/null | tail -n +2 | tail -n 1`  # don't take iter_0 snapshot though
if [ "$lastfile" = "" ]; then
    echo "Starting training from scratch"
else
    echo "Resuming training from file: $lastfile"
fi


try=1
set +e       # Don't exit immediately on errors
while : ; do
    echo "Attempt number: $try"
    echo "-------------------------------------------------"

    if [ "$finetune_base_net_file" = "" ]; then
        if [ "$lastfile" = "" ]; then
            echo "Fine-tuning: no. Resuming: no"
        else
            echo "Fine-tuning: no. Resuming: yes"
        fi
        # same command for both because lastfile could be blank
        GLOG_logtostderr=1 time ./train_net.bin imagenet_solver.prototxt $lastfile 2>&1
        code="$?"
    else
        if [ "$lastfile" = "" ]; then
            echo "Fine-tuning: yes. Resuming: no"
            GLOG_logtostderr=1 time ./finetune_net.bin imagenet_solver.prototxt $finetune_base_net_file 2>&1
            code="$?"
        else
            echo "Fine-tuning: yes. Resuming: yes"
            # In this case we don't use ./finetune_net.bin or the
            # finetune_base_net_file, because we're resuming a
            # previous fine-tune run, so we just need the
            # *.solverstate file
            GLOG_logtostderr=1 time ./train_net.bin imagenet_solver.prototxt $lastfile 2>&1
            code="$?"
        fi
    fi

    [ "$code" = "0" ] && break
    timeout=$(($try*5))
    echo "Failed with code $code, sleeping for $timeout..."
    sleep $timeout
    echo 
    echo
    if [ "$try" = "10" ]; then
        subj="Failed $try times at job `cat jobname`"
        ssh mmmlog3 mailj "$subj"
        echo "Sent mail; giving up"
        break
    fi
    try=$((try+1))
done


echo "-------------------------------------------------"
echo "Finished (last exit code: $code)."
