#! /bin/bash

echo 'Do not run this! This is just a place to copy and paste commands that have been used to start experiments'
exit 1





##########################
# Transfer experiments
##########################

for split in 0 1 2 3; do
    for layer in 1 2 3 4 5 6 7; do
        resman -r transfer${split}A${split}B_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}B_train/leveldb ../../data/ilsvrc12/data/half${split}B_valid/leveldb ../../data/ilsvrc12/data/half${split}A_train/mean.binaryproto results/*half${split}A/
        sleep 2
        resman -r transfer${split}B${split}A_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}A_train/leveldb ../../data/ilsvrc12/data/half${split}A_valid/leveldb ../../data/ilsvrc12/data/half${split}B_train/mean.binaryproto results/*half${split}B/
        sleep 2
        resman -r transfer${split}A${split}A_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}A_train/leveldb ../../data/ilsvrc12/data/half${split}A_valid/leveldb ../../data/ilsvrc12/data/half${split}A_train/mean.binaryproto results/*half${split}A/
        sleep 2
        resman -r transfer${split}B${split}B_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}B_train/leveldb ../../data/ilsvrc12/data/half${split}B_valid/leveldb ../../data/ilsvrc12/data/half${split}B_train/mean.binaryproto results/*half${split}B/
        sleep 2
    done
done

for dir in results/*transfer*_1_*; do
    echo $dir
    cd $dir
    ./0_cpln_data
    cd -
done

# edit imagenet_train.prototxt  to      set lr and weight decay to 0 for layer 1, then run
for dir in results/*transfer*_1_1; do cp -v imagenet_train.prototxt $dir/; done
# edit imagenet_train.prototxt  to also set lr and weight decay to 0 for layer 2, then run
for dir in results/*transfer*_1_2; do cp -v imagenet_train.prototxt $dir/; done
# edit imagenet_train.prototxt  to also set lr and weight decay to 0 for layer 3, then run
for dir in results/*transfer*_1_3; do cp -v imagenet_train.prototxt $dir/; done
# etc....


perl -p -i -e 's/conv2/conv2-new/g' results/*transfer*_1_1/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv3/conv3-new/g' results/*transfer*_1_[1-2]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv4/conv4-new/g' results/*transfer*_1_[1-3]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv5/conv5-new/g' results/*transfer*_1_[1-4]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc6/fc6-new/g'     results/*transfer*_1_[1-5]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc7/fc7-new/g'     results/*transfer*_1_[1-6]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc8/fc8-new/g'     results/*transfer*_1_[1-7]/imagenet_{train,val}.prototxt





##########################
# [2014-05-07 11:32:25 am] 
# Transfer-ft experiments
##########################

for split in 0 1 2 3; do
    for layer in 1 2 3 4 5 6 7; do
        resman -r transfer-ft${split}A${split}B_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}B_train/leveldb ../../data/ilsvrc12/data/half${split}B_valid/leveldb ../../data/ilsvrc12/data/half${split}A_train/mean.binaryproto results/*half${split}A/
        sleep 2
        resman -r transfer-ft${split}B${split}A_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}A_train/leveldb ../../data/ilsvrc12/data/half${split}A_valid/leveldb ../../data/ilsvrc12/data/half${split}B_train/mean.binaryproto results/*half${split}B/
        sleep 2
        resman -r transfer-ft${split}A${split}A_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}A_train/leveldb ../../data/ilsvrc12/data/half${split}A_valid/leveldb ../../data/ilsvrc12/data/half${split}A_train/mean.binaryproto results/*half${split}A/
        sleep 2
        #resman -r transfer-ft${split}B${split}B_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/half${split}B_train/leveldb ../../data/ilsvrc12/data/half${split}B_valid/leveldb ../../data/ilsvrc12/data/half${split}B_train/mean.binaryproto results/*half${split}B/
        #sleep 2
    done
done

for dir in results/*transfer-ft*_1_*; do
    echo $dir
    cd $dir
    ./0_cpln_data
    cd -
done

# Because we're finetuning the networks, we leave all lr and weight
# decays at their original values! So just run:
for dir in results/*transfer-ft*_1_*; do cp -v imagenet_train.prototxt $dir/; done

perl -p -i -e 's/conv2/conv2-new/g' results/*transfer-ft*_1_1/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv3/conv3-new/g' results/*transfer-ft*_1_[1-2]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv4/conv4-new/g' results/*transfer-ft*_1_[1-3]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv5/conv5-new/g' results/*transfer-ft*_1_[1-4]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc6/fc6-new/g'     results/*transfer-ft*_1_[1-5]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc7/fc7-new/g'     results/*transfer-ft*_1_[1-6]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc8/fc8-new/g'     results/*transfer-ft*_1_[1-7]/imagenet_{train,val}.prototxt




##########################
# [2014-05-21 11:24:35 pm] 
# Semantic Split Transfer experiments
##########################

resman -r halfnatmanA ./create_run_dir_fresh ../../data/ilsvrc12/data/halfnatmanA_train/leveldb ../../data/ilsvrc12/data/halfnatmanA_valid/leveldb ../../data/ilsvrc12/data/halfnatmanA_train/mean.binaryproto
resman -r halfnatmanB ./create_run_dir_fresh ../../data/ilsvrc12/data/halfnatmanB_train/leveldb ../../data/ilsvrc12/data/halfnatmanB_valid/leveldb ../../data/ilsvrc12/data/halfnatmanB_train/mean.binaryproto

jyosinsk@mmmlog3 [~/s/caffe/examples/imagenet/results/140521_233227_b9536f2_priv_halfnatmanB] $ ./0_cpln_data
jyosinsk@mmmlog3 [~/s/caffe/examples/imagenet/results/140521_233227_b9536f2_priv_halfnatmanB] $ cp ../../imagenet_solver_4d.prototxt imagenet_solver.prototxt
jyosinsk@mmmlog3 [~/s/caffe/examples/imagenet/results/140521_233127_b9536f2_priv_halfnatmanA] $ ./0_cpln_data
jyosinsk@mmmlog3 [~/s/caffe/examples/imagenet/results/140521_233127_b9536f2_priv_halfnatmanA] $ cp ../../imagenet_solver_4d.prototxt imagenet_solver.prototxt

# [2014-05-29  9:17:55 pm] 
# Semantic Split Transfer experiments - second part

for layer in 1 2 3 4 5 6 7; do
    resman -r transfernatmanAB_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanB_train/leveldb ../../data/ilsvrc12/data/halfnatmanB_valid/leveldb ../../data/ilsvrc12/data/halfnatmanA_train/mean.binaryproto results/*halfnatmanA/
    sleep 2
    resman -r transfernatmanBA_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanA_train/leveldb ../../data/ilsvrc12/data/halfnatmanA_valid/leveldb ../../data/ilsvrc12/data/halfnatmanB_train/mean.binaryproto results/*halfnatmanB/
    sleep 2

    resman -r transfernatmanAA_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanA_train/leveldb ../../data/ilsvrc12/data/halfnatmanA_valid/leveldb ../../data/ilsvrc12/data/halfnatmanA_train/mean.binaryproto results/*halfnatmanA/
    sleep 2
    resman -r transfernatmanBB_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanB_train/leveldb ../../data/ilsvrc12/data/halfnatmanB_valid/leveldb ../../data/ilsvrc12/data/halfnatmanB_train/mean.binaryproto results/*halfnatmanB/
    sleep 2
done


for dir in results/*transfernatman??_1_*; do
    echo $dir
    cd $dir
    ./0_cpln_data
    cp -v ../*halfnatmanA/imagenet_solver.prototxt .   # faster solver.proto
    cd -
done

# edit imagenet_train.prototxt  to      set lr and weight decay to 0 for layer 1, then run
for dir in results/*transfernatman*_1_1; do cp -v imagenet_train.prototxt $dir/; done
# edit imagenet_train.prototxt  to also set lr and weight decay to 0 for layer 2, then run
for dir in results/*transfernatman*_1_2; do cp -v imagenet_train.prototxt $dir/; done
# edit imagenet_train.prototxt  to also set lr and weight decay to 0 for layer 3, then run
for dir in results/*transfernatman*_1_3; do cp -v imagenet_train.prototxt $dir/; done
# etc....


perl -p -i -e 's/conv2/conv2-new/g' results/*transfernatman*_1_1/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv3/conv3-new/g' results/*transfernatman*_1_[1-2]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv4/conv4-new/g' results/*transfernatman*_1_[1-3]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv5/conv5-new/g' results/*transfernatman*_1_[1-4]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc6/fc6-new/g'     results/*transfernatman*_1_[1-5]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc7/fc7-new/g'     results/*transfernatman*_1_[1-6]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc8/fc8-new/g'     results/*transfernatman*_1_[1-7]/imagenet_{train,val}.prototxt


# [2014-06-01 10:03:44 pm] 
# Semantic Split Transfer experiments - third part - ft

for layer in 1 2 3 4 5 6 7; do
    resman -r transfer-ftnatmanAB_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanB_train/leveldb ../../data/ilsvrc12/data/halfnatmanB_valid/leveldb ../../data/ilsvrc12/data/halfnatmanA_train/mean.binaryproto results/*halfnatmanA/
    sleep 2
    resman -r transfer-ftnatmanBA_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanA_train/leveldb ../../data/ilsvrc12/data/halfnatmanA_valid/leveldb ../../data/ilsvrc12/data/halfnatmanB_train/mean.binaryproto results/*halfnatmanB/
    sleep 2

    resman -r transfer-ftnatmanAA_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanA_train/leveldb ../../data/ilsvrc12/data/halfnatmanA_valid/leveldb ../../data/ilsvrc12/data/halfnatmanA_train/mean.binaryproto results/*halfnatmanA/
    sleep 2
    #resman -r transfer-ftnatmanBB_1_$layer ./create_run_dir_transfer ../../data/ilsvrc12/data/halfnatmanB_train/leveldb ../../data/ilsvrc12/data/halfnatmanB_valid/leveldb ../../data/ilsvrc12/data/halfnatmanB_train/mean.binaryproto results/*halfnatmanB/
    #sleep 2
done

for dir in results/*transfer-ftnatman*_1_*; do
    echo $dir
    cd $dir
    cp -v ../*halfnatmanA/imagenet_solver.prototxt .   # faster solver.proto
    ./0_cpln_data
    cd -
done

# Because we're finetuning the networks, we leave all lr and weight
# decays at their original values! So just run:
for dir in results/*transfer-ftnatman*_1_*; do cp -v imagenet_train.prototxt $dir/; done

perl -p -i -e 's/conv2/conv2-new/g' results/*transfer-ftnatman*_1_1/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv3/conv3-new/g' results/*transfer-ftnatman*_1_[1-2]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv4/conv4-new/g' results/*transfer-ftnatman*_1_[1-3]/imagenet_{train,val}.prototxt
perl -p -i -e 's/conv5/conv5-new/g' results/*transfer-ftnatman*_1_[1-4]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc6/fc6-new/g'     results/*transfer-ftnatman*_1_[1-5]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc7/fc7-new/g'     results/*transfer-ftnatman*_1_[1-6]/imagenet_{train,val}.prototxt
perl -p -i -e 's/fc8/fc8-new/g'     results/*transfer-ftnatman*_1_[1-7]/imagenet_{train,val}.prototxt





##########################
# [2014-05-22  3:05:08 pm] 
# Reduced training set experiments
##########################



for size in 0001 0002 0005 0010 0025 0050 0100 0250 0500 0750 1000; do
    resman -r reduced-${size} ./create_run_dir_fresh ../../data/ilsvrc12/data/reduced${size}_train/leveldb ../../data/ilsvrc12/data/whole_valid/leveldb ../../data/ilsvrc12/data/reduced${size}_train/mean.binaryproto
    sleep 2
done
# And a run with the full size dataset, but with faster training via imagenet_solver_4d.prototxt
resman -r reduced-1300 ./create_run_dir_fresh ../../data/ilsvrc12/data/whole_train/leveldb ../../data/ilsvrc12/data/whole_valid/leveldb ../../data/ilsvrc12/data/whole_train/mean.binaryproto

# Important: copy fast imagenet_solver_4d.prototxt to directory!
for dir in results/*reduced-*; do
    echo $dir
    cd $dir
    cp -v ../../imagenet_solver_4d.prototxt imagenet_solver.prototxt
    ./0_cpln_data
    ./1_submit_train 120:00:00
    cd -
done

# [2014-06-01  9:35:14 pm]  Debugging failed reduced-1300 run:
resman -r reduced-1300-2 ./create_run_dir_fresh ../../data/ilsvrc12/data/whole_train/leveldb ../../data/ilsvrc12/data/whole_valid/leveldb ../../data/ilsvrc12/data/whole_train/mean.binaryproto
resman -r reduced-1300-2o ./create_run_dir_fresh ../../data/ilsvrc12/data/old_master_whole_train/leveldb ../../data/ilsvrc12/data/whole_valid/leveldb ../../data/ilsvrc12/data/whole_train/mean.binaryproto
resman -r reduced-1300-2om ./create_run_dir_fresh ../../data/ilsvrc12/data/old_master_whole_train/leveldb ../../data/ilsvrc12/data/whole_valid/leveldb ../../data/ilsvrc12/fetched/FETCHED_imagenet_mean.binaryproto


